# Generated by Django 5.2.4 on 2025-07-12 06:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre_empresa', models.CharField(max_length=150, unique=True)),
                ('colonia_empresa', models.CharField(max_length=100)),
                ('calle_empresa', models.CharField(max_length=100)),
                ('codigo_postal_empresa', models.CharField(max_length=10)),
                ('num_externo_empresa', models.CharField(max_length=5)),
                ('num_interno_empresa', models.CharField(blank=True, max_length=5, null=True)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('estado_empresa', models.CharField(choices=[('Mexicali', 'Mexicali'), ('Tijuana', 'Tijuana'), ('Ensenada', 'Ensenada'), ('Tecate', 'Tecate'), ('Playas de rosarito', 'Playas de rosarito')], default='Tijuana', max_length=25)),
                ('telefono_empresa', models.CharField(max_length=10, unique=True)),
                ('giro_empresa', models.CharField(max_length=100)),
                ('tamano_empresa', models.CharField(choices=[('Grande', 'Grande'), ('Mediana', 'Mediana')], default='Mediana', max_length=25)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='ProductosEmpresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_empresa_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('alias_producto', models.CharField(max_length=100)),
                ('horas_uso_diario', models.FloatField()),
                ('dias_uso_mensual', models.FloatField()),
                ('ubicacion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'productos_empresas',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre_sucursal', models.CharField(max_length=100, unique=True)),
                ('colonia_sucursal', models.CharField(max_length=100)),
                ('calle_sucursal', models.CharField(max_length=100)),
                ('codigo_postal_sucursal', models.CharField(max_length=10)),
                ('num_externo_sucursal', models.CharField(max_length=5)),
                ('num_interno_sucursal', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'sucursal',
            },
        ),
        migrations.CreateModel(
            name='SucursalProductosEmpresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'sucursal_productos_empresas',
            },
        ),
    ]
