# Generated by Django 5.2.4 on 2025-07-12 06:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_initial'),
        ('subscripciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoSubscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia'), ('PayPal', 'PayPal')], max_length=50)),
                ('estado_pago', models.CharField(choices=[('Exitoso', 'Exitoso'), ('Pendiente', 'Pendiente'), ('Fallido', 'Fallido')], default='Pendiente', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('subscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscripciones.subscripcion')),
            ],
            options={
                'db_table': 'pago_subscripcion',
            },
        ),
    ]
