# Generated by Django 5.2.4 on 2025-07-12 06:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre_producto', models.CharField(max_length=255, unique=True)),
                ('marca_producto', models.CharField(max_length=50, unique=True)),
                ('modelo_producto', models.CharField(max_length=50, unique=True)),
                ('consumo_kw', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
            options={
                'db_table': 'catalogo',
            },
        ),
    ]
