# Generated by Django 5.2.4 on 2025-07-12 06:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboCfe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibo_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('periodo_factura_inicio', models.DateField()),
                ('periodo_factura_final', models.DateField()),
                ('indicador_consumo', models.CharField(choices=[('Muy Bajo', 'Muy Bajo'), ('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto'), ('Muy alto', 'Muy alto')], max_length=100)),
                ('lectura_anterior', models.FloatField()),
                ('lectura_actual', models.FloatField()),
            ],
            options={
                'db_table': 'recibo_cfe',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporte_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reporte_consumo', models.FloatField()),
                ('fecha_inicio_reporte', models.DateField()),
                ('fecha_final_reporte', models.DateField()),
                ('fecha_generacion_reporte', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reporte',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre_ticket', models.CharField(max_length=100)),
                ('descripcion_ticket', models.CharField(blank=True, max_length=256, null=True)),
                ('estado_ticket', models.BooleanField()),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mantenimiento_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_mantenimiento', models.DateField()),
                ('tipo_mantenimiento', models.CharField(max_length=100)),
                ('estado_equipo', models.CharField(choices=[('Excelente', 'Excelente'), ('Muy buena', 'Muy buena'), ('Regular', 'Regular'), ('Mala', 'Mala'), ('Muy mala', 'Muy mala')], max_length=50)),
                ('proximo_mantenimiento', models.DateField()),
                ('producto_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.productosempresas')),
            ],
            options={
                'db_table': 'mantenimiento',
            },
        ),
    ]
