# Generated by Django 5.2.4 on 2025-07-12 06:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscripcion_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_pago', models.DateField()),
                ('siguiente_pago', models.DateField()),
                ('estatus_sub', models.BooleanField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'db_table': 'subscripcion',
            },
        ),
    ]
