# Generated by Django 5.2.4 on 2025-07-17 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_initial'),
        ('usuarios', '0002_usuario_especialidad_usuario_rol_usuario_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tecnico',
            old_name='apellido_tecnico',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='tecnico',
            old_name='correo_tecnico',
            new_name='email_user',
        ),
        migrations.RenameField(
            model_name='tecnico',
            old_name='nombre_tecnico',
            new_name='nombres',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='telefono_tecnico',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.AddField(
            model_name='tecnico',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='telefono',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.sucursal'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='tipo_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.tipotecnico'),
        ),
    ]
